### ISSUE TITLE
Handle multiple Grafana Cloud Accounts

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/akdc#116]
With the plan to have separate Grafana Cloud accounts for each tenant, how should we handle adding the fluent bit and prometheus secrets during cluster creation?

Currently, we store the secrets in key vault, have the vm get the values from key vault using MI, then set the k8s secrets with those values.

Plan:
- Update the kv secret values to be "generic" for prom, fluent bit, and ssl certs
- Update fleet-vm.templ to use new kv secret names
- New names:
  - prometheus-secret
  - fluent-bit-secret
  - ssl-cert
  - ssl-key

**Comment by aflinchb** [comment]
Update: current approach is storing the secrets in key vault, having the vm get the values from key vault using MI, then setting the k8s secrets.

**Comment by aflinchb** [comment]
Since it is key vault based, it may make sense to add additional parameter/variable values for the fluent bit + prometheus secret names to createVMSetupScript in the create command and in the templ file.  We could also potentially create a new KV for each fleet, pass the kv name as a parameter, and always keep the secret names the same.

I'm also realizing we may likely want a different MI for each fleet (Kevin and I just updated the edge-gitops repo with the CS Secret for the MI we have been using for the VMs)
